### ISSUE TITLE
could not determine a constructor for the tag '!env' or '!time' / Config is not valid

### ISSUE THREAD

**Issue by trattaa** [JuniorJPDJ/telegram-rss#14]
Hey @JuniorJPDJ !
I was looking for a bot for iTunes podcasts. А very small number of bots, which displays a description, so accidentally came to this bot. I decided to install the telethon branch, but I constantly encounter problems launching it. I am new to Linux and therefore it was difficult to make Python 3.8 by default, otherwise tortoise-orm did not install on Python 3.6 which is by default. I solved this problem, but now I'm stuck on main.py launch itself. First I’ll attach my config.yml so that everything is clear.
[config.zip](https://github.com/JuniorJPDJ/telegram-rss/files/4807561/config.zip)
so i run "./main.py" and he gives an error:
`Traceback (most recent call last):
  File "./main.py", line 217, in <module>
    main()
  File "./main.py", line 177, in main
    config = yaml.safe_load(f)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!env'
  in "config.yml", line 18, column 12`
I comment on this line, although I know that this is not correct, He likewise complains about !time, i translate time into seconds format (min_check_interval: 60 and etc) and now it gives an error:
`Traceback (most recent call last):
  File "./main.py", line 217, in <module>
    main()
  File "./main.py", line 179, in main
    raise Exception("Config is not valid")
Exception: Config is not valid`
it is clear that my config is not correct now, but what needs to be done so that it understands the attributes !env and !time, i tried to update PyYAML

> sudo -H pip3 install --upgrade PyYAML

`Requirement already up-to-date: PyYAML in /usr/local/lib/python3.8/dist-packages (5.3.1)`

please help me, what needs to be done to launch your bot?

**Comment by trattaa** [comment]
And another question, does the bot support its work in the chat?

**Comment by JuniorJPDJ** [comment]
Branch you are using is now work in progress.
It's not complete and it's rather far from being one :/
