### ISSUE TITLE
PornHub RSS breaks the bot

### ISSUE THREAD

**Issue by mattroot** [JuniorJPDJ/telegram-rss#3]
this is an important thing.

ok seriously when the bot sees a feed without an id for each post it fucks itself up (maybe it's just fapping idk)

AAAAAAAAAAAAAANYWAY https://www.pornhub.com/rss

**Comment by JuniorJPDJ** [comment]
Thanks for the report :D
I will workaround this in few minutes.

I confirmed the issue:
```
2019-07-10 22:17:21,233 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/juniorjpdj/.virtualenvs/telegram-rss/lib/python3.7/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/juniorjpdj/Cloud/dev/Python/telegram-rss/main.py", line 101, in download_feed
    if entry["id"] not in history[url]:
  File "/home/juniorjpdj/.virtualenvs/telegram-rss/lib/python3.7/site-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'id'
```
